name: Automation

on:
  push:
    branches: [ Beta ]
  pull_request:
    branches: [ Beta ]

jobs:
  build-and-test:
    runs-on: macos-latest
    
    steps:
      - uses: checkout@v2
        
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_13.app

      - name: Build
        run: xcodebuild clean build CICD Sample
