name: Automation

on: push

jobs:
  super-lint:
    runs-on: macos
      steps:
        - name: checkout 
          uses: checkout@v2
        - name: Run Automation
          uses: github/super-linter@v3
            env: 
            DEFAULT_BRANCH: main
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      
