name: Automation

on:
  push:
    branches: [ Beta ]
  pull_request:
    branches: [ Beta ]

jobs:
  build-and-test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Force Xcode 13
      run: sudo xcode-select -switch /Applications/Xcode_13.0.app
    - name: Build App
      working-directory: CICD Sample
      run: xcodebuild build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
