name: Automation

on: push

jobs:
  build-and-test:
    runs-on: macos-latest
    
      steps:
        - uses: checkout@v2
        
        
        - name: Run Automation
          uses: github/super-linter@v3
            env: 
            DEFAULT_BRANCH: main
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
