name: Automation

on:
  push:
    branches: [ Beta ]
  pull_request:
    branches: [ Beta ]

jobs:
  build-and-test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Force Xcode 11
      run: sudo xcode-select -switch /Applications/Xcode_13.0.app
    - name: Build App
      run: xcodebuild -project "CICD Sample.xcodeproj" -scheme "GActions-Test" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=N
