name: Automation

on:
  push:
    branches: [ Beta ]
  pull_request:
    branches: [ Beta ]

jobs:
  build-and-test:
    runs-on: macos-latest
    
    steps:
      - uses: checkout@v2
        
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_13.app

      - name: Build
        run: xcodebuild clean build test -project GActions-Test/CICD Sample.xcodeproj -scheme "GActions-Test" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPad Pro (12.9-inch) (5th generation)" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
